server:
  port: 8081

spring:
  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: "http://discoveryservice:8761/eureka/"
    registerWithEureka: true
    instance:
      metadataMap:
        instanceId: ${spring.application.name}:${random.value}

