server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka

eureka:
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: true
  client:
    serviceUrl:
      defaultZone: http://discoveryservice:8761/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
