spring:
  application:
    name: eureka

server:
  port: ${PORT:8761}

eureka:
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: true
  client:
    registerWithEureka: true
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
