discoveryservice:
  build: ./discovery-service
  ports:
    - "8761:8761"
  volumes:
    - /services:/services

userservice:
  build: ./user-service
  ports:
    - "8081:8081"
  volumes:
    - /services:/services
  links:
    - discoveryservice

zuulservice:
  build: ./zuul-service
  ports:
    - "8080:8080"
  volumes:
    - /services:/services
  links:
    - discoveryservice

