server:
  port: 8080

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryservice:8761/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}